get statement,a query string
ofeterovskaya/node-express-course pull request #3
Opened 2024-03-11 04:47 UTC by ofeterovskaya

2024-03-13 18:05 UTC, mattcarlotta requested changes
Excellent work, Oksana! You did **extremely** well on this assignment. However, before I can approve this PR, there's one callout below that need to be addressed.

### When you've addressed the feedback below, please do NOT resubmit your assignment using the CTD form. Instead, send me a DM when this PR is ready for another review.

2024-03-13 18:05 UTC, mattcarlotta commented on 02-express-tutorial/app.js
> +  }
Nitpick (doesn't require changes):
I like to avoid if/else statements for 2 conditions and instead, either use early returns for errors/invalid responses:
```js
if (!product) {
  return res.status(404).json({ message: "That product was not found." });
}

return res.json(product);
```
OR, use a ternary operator:
```js
return !product
  ? res.status(404).json({ message: "That product was not found." }) 
  : res.json(product);
```

2024-03-13 18:05 UTC, mattcarlotta commented on 02-express-tutorial/app.js
> +
Requires change:
This logic can be simplified using [Array.reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce).
```js
app.get('/api/v1/query', (req, res) => {
    const { search, limit = 0, maxPrice = 0 } = req.query;

    // use Array.reduce to build a list of filtered products
    const filteredProducts = products.reduce((acc, product) => {
        // if the product price is greater than maxPrice OR
        // if there's a search and the product name doesn't include the search term
        // then return the accumulator (acc === list of filtered products)
        if (
            product.price > parseFloat(maxPrice) || 
            (search && !product.name.includes(search))
        ) {
            return acc;
        }

        // if the accumulator (acc === list of filtered products) is less than the limit, add product to the list
        if (limit && acc.length < parseInt(limit, 10)) {
            acc.push(product);
        }

        // return the accumulator (acc === list of filtered products) to check the next product
        return acc;
    }, []);

    res.status(200).json(filteredProducts);
});
```

2024-03-13 18:05 UTC, mattcarlotta commented on 02-express-tutorial/public/index.html
> +    <script>
Nitpick (doesn't require change):
This script tag should have a [type="module"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type), which is a deferred JavaScript script.

2024-03-13 18:05 UTC, mattcarlotta commented on 02-express-tutorial/public/index.html
> +        });
Nitpick (doesn't require changes):
If there's ever an error in the API response, we want to make sure that error is communicated to the user. I'd recommend that we handle the error and display a user friendly error message that states "Unable to load products, please try again later."

2024-03-13 18:05 UTC, mattcarlotta commented on 02-express-tutorial/public/index.html
> +        document.getElementById('loadProducts').addEventListener('click', async () => {
Nitpick (doesn't require change):
When using document selectors, it's always best to check if the selector node is defined before using methods. For example, if you happen to misspell an id, then you'll get an error logged to the console that states `can't read property "addEventListener" of undefined`.

2024-03-14 20:48 UTC, ofeterovskaya commented on 02-express-tutorial/app.js
> +  }
Thank you Matt for suggestion

2024-03-15 00:02 UTC, mattcarlotta approved these changes
Looks good to me! Great work, Oksana! 🥳🎊🎉

2024-03-15 00:04 UTC, merged